// Mocks generated by Mockito 5.2.0 from annotations
// in project_alta/test/Data_API/kategori_data_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:project_alta/Data_API/kategori_data.dart' as _i2;
import 'package:project_alta/Model/katgori_model.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [CategorieData].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategorieData extends _i1.Mock implements _i2.CategorieData {
  MockCategorieData() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.CategorieModel>> getcategories() => (super.noSuchMethod(
          Invocation.method(#getcategories, []),
          returnValue:
              Future<List<_i4.CategorieModel>>.value(<_i4.CategorieModel>[]))
      as _i3.Future<List<_i4.CategorieModel>>);
}
